### ISSUE TITLE
Hw2_report

### ISSUE THREAD

**Issue by tchanyaswad** [supersergiy/hw2_COS424#1]

**Comment by supersergiy** [comment]
should we do it in google doc first and translate to latex later?

**Comment by tchanyaswad** [comment]
I actually didn't mean to create the issues in git. that's my mistake. haha

We can do it on google doc as well, or we can just do it on the hw2_report file I created on the repository. I'm fine either way. The git way is a bit more convenient for me tho.

Cheers,

Theerachai Chanyaswad (Thee)
Electrical Engineering, Princeton University
tc7@princeton.edu
t.chanyaswad@gmail.com

**Comment by supersergiy** [comment]
if we use git it will be hard for both of us to modify a file at the same
time,
cause we'll have to go through a merging process.
let's do google doc better

**Comment by tchanyaswad** [comment]
You actually don't modify the report file. You just write your section and put it up in a separate file. Then, right when we are about to submit, we just put them together. I don't think modifying the same file on google doc is a good idea either. What do you think?

Theerachai Chanyaswad (Thee)
Electrical Engineering, Princeton University
tc7@princeton.edu
t.chanyaswad@gmail.com

**Comment by supersergiy** [comment]
modifying the same file on the google doc always worked for me.
anyway, I've had my dinner now, what about you?
